Repository vuejs/language-tools, pull requests merged in 2024-12, with the labels that each got.

#4969 fix(language-core): correct type and completion support of `vue:` event
  packages/language-core/lib/codegen/template/elementEvents.ts
  packages/language-core/lib/codegen/template/elementProps.ts
  packages/language-service/lib/plugins/vue-template.ts
Labels: 🍰 p2-nice-to-have, ready for review

#5053 refactor(language-service): consistent style of source and virtual code operation
  packages/language-service/lib/ideFeatures/nameCasing.ts
  packages/language-service/lib/plugins/vue-autoinsert-dotvalue.ts
  packages/language-service/lib/plugins/vue-complete-define-assignment.ts
  packages/language-service/lib/plugins/vue-document-drop.ts
  packages/language-service/lib/plugins/vue-document-links.ts
  packages/language-service/lib/plugins/vue-extract-file.ts
  packages/language-service/lib/plugins/vue-inlayhints.ts
  packages/language-service/lib/plugins/vue-sfc.ts
  packages/language-service/lib/plugins/vue-template.ts
  packages/language-service/lib/plugins/vue-twoslash-queries.ts
  packages/typescript-plugin/lib/common.ts
  packages/typescript-plugin/lib/requests/collectExtractProps.ts
Labels: ready for review, 🧹 p1-chore

#4987 feat(language-core): support the use of sfc root comment to configure `vueCompilerOptions`
  extensions/vscode/syntaxes/vue.tmLanguage.json
  packages/language-core/lib/codegen/script/scriptSetup.ts
  packages/language-core/lib/parsers/scriptSetupRanges.ts
  packages/language-core/lib/parsers/vueCompilerOptions.ts
  packages/language-core/lib/plugins/file-html.ts
  packages/language-core/lib/plugins/vue-tsx.ts
  packages/language-core/lib/types.ts
  packages/language-core/lib/utils/parseSfc.ts
  packages/language-core/lib/utils/ts.ts
  packages/language-core/lib/virtualFile/computedSfc.ts
  test-workspace/tsc/passedFixtures/vue3.4/defineProp_B/script-setup-generic.vue
  test-workspace/tsc/passedFixtures/vue3.4/defineProp_B/script-setup.vue
  test-workspace/tsc/passedFixtures/vue3/#3548/main.vue
  test-workspace/tsc/passedFixtures/vue3/#4649/prop-comp.vue
  test-workspace/tsc/passedFixtures/vue3/defineProp_A/script-setup.vue
  test-workspace/tsc/passedFixtures/vue3/defineProp_B/script-setup-generic.vue
  test-workspace/tsc/passedFixtures/vue3/defineProp_B/script-setup.vue
Labels: ready to merge, version: minor

#5048 feat(vscode): add timeout logic for insiders fetching
  extensions/vscode/src/insiders.ts
Labels: 🍰 p2-nice-to-have, ready to merge

#5049 fix(language-core): prevent visiting functional components for parseScriptSetupRanges
  packages/language-core/lib/parsers/scriptSetupRanges.ts
  test-workspace/tsc/passedFixtures/vue3/templateRef/main.vue
Labels: 🔩 p2-edge-case, ready to merge

#5052 fix(language-service): don't provide modifier completion for `@` and `:`
  packages/language-service/lib/plugins/vue-template.ts
Labels: 🍰 p2-nice-to-have, ready to merge

#5067 fix(language-core): resolve components with various name cases correctly
  packages/language-core/lib/codegen/template/element.ts
  packages/language-core/lib/codegen/template/index.ts
  test-workspace/tsc/passedFixtures/vue3_strictTemplate/#5067/comp.vue
  test-workspace/tsc/passedFixtures/vue3_strictTemplate/#5067/main.vue
Labels: 🍰 p2-nice-to-have, ready for review

#5078 refactor(language-core): simplify current component info passing
  packages/language-core/lib/codegen/template/context.ts
  packages/language-core/lib/codegen/template/element.ts
  packages/language-core/lib/codegen/template/elementChildren.ts
  packages/language-core/lib/codegen/template/index.ts
  packages/language-core/lib/codegen/template/slotOutlet.ts
  packages/language-core/lib/codegen/template/templateChild.ts
  packages/language-core/lib/codegen/template/vFor.ts
  packages/language-core/lib/codegen/template/vIf.ts
Labels: ready for review, 🧹 p1-chore

#5056 feat(language-core): navigation support for `$attrs`, `$slots`, `$refs` and `$el` in the template
  packages/language-core/lib/codegen/script/template.ts
  packages/language-core/lib/codegen/template/context.ts
  packages/language-core/lib/codegen/template/element.ts
  packages/language-core/lib/codegen/template/elementProps.ts
  packages/language-core/lib/codegen/template/index.ts
  packages/language-core/lib/codegen/template/interpolation.ts
  packages/language-core/lib/plugins/vue-tsx.ts
Labels: 🍰 p2-nice-to-have, ready for review

#5077 fix(language-core): do not generate element for `<template>` with `v-slot`
  packages/language-core/lib/codegen/globalTypes.ts
  packages/language-core/lib/codegen/template/context.ts
  packages/language-core/lib/codegen/template/element.ts
  packages/language-core/lib/codegen/template/elementChildren.ts
  packages/language-core/lib/codegen/template/templateChild.ts
  packages/language-core/lib/codegen/template/vSlot.ts
Labels: 🍰 p2-nice-to-have, ready for review

#4989 feat(language-service): support global directives completion
  packages/language-service/index.ts
  packages/language-service/lib/plugins/vue-template.ts
  packages/typescript-plugin/lib/client.ts
  packages/typescript-plugin/lib/requests/componentInfos.ts
  packages/typescript-plugin/lib/server.ts
Labels: 🍰 p2-nice-to-have, ready for review

#5096 fix(language-service): set code action kinds to avoid warning
  packages/language-service/lib/plugins/vue-extract-file.ts
Labels: 🍰 p2-nice-to-have, ready for review

#5086 fix(language-service): read ast from codegen instead of parsing it repeatedly
  packages/language-core/index.ts
  packages/language-service/lib/plugins/utils.ts
  packages/language-service/lib/plugins/vue-autoinsert-dotvalue.ts
  packages/language-service/lib/plugins/vue-complete-define-assignment.ts
  packages/language-service/lib/plugins/vue-document-drop.ts
  packages/language-service/lib/plugins/vue-extract-file.ts
  packages/language-service/lib/plugins/vue-template.ts
Labels: 🍰 p2-nice-to-have, ready for review
