Repository vuejs/language-tools, pull requests merged in 2025-01, with the labels that each got.

#5113 fix(language-core): intersect local `$attrs` with `__VLS_ctx.$attrs`
  packages/language-core/lib/codegen/template/index.ts
  test-workspace/tsc/passedFixtures/#5111/main.vue
  test-workspace/tsc/passedFixtures/#5111/tsconfig.json
Labels: 🔨 p3-minor-bug, ready for review

#5134 feat(language-service): display deprecated info of props in completion
  packages/language-service/lib/plugins/vue-template.ts
  packages/typescript-plugin/lib/requests/componentInfos.ts
  packages/typescript-plugin/lib/server.ts
  packages/typescript-plugin/lib/utils.ts
Labels: 🍰 p2-nice-to-have, ready for review

#5101 feat(component-meta): collect destructured props defaults
  packages/component-meta/lib/base.ts
  packages/component-meta/tests/index.spec.ts
  packages/language-core/lib/codegen/utils/index.ts
  packages/language-core/lib/parsers/scriptSetupRanges.ts
  packages/language-core/lib/plugins/vue-tsx.ts
  packages/language-service/lib/plugins/vue-inlayhints.ts
  packages/tsc/tests/__snapshots__/dts.spec.ts.snap
  test-workspace/component-meta/reference-type-props/component-destructure.vue
Labels: 🍰 p2-nice-to-have, ready for review

#5100 fix(language-plugin-pug): ignore duplicate attribute error of `class`
  packages/language-plugin-pug/index.ts
  test-workspace/tsc/passedFixtures/pug/#5099.vue
Labels: 🍰 p2-nice-to-have, ready for review

#5084 fix(language-core): align types of `v-for` with core
  packages/language-core/lib/codegen/globalTypes.ts
  test-workspace/tsc/passedFixtures/shared.d.ts
  test-workspace/tsc/passedFixtures/vue3/v-for/main.vue
Labels: ready for review, 🧹 p1-chore
