Repository vuejs/language-tools, pull requests merged in 2025-03, with the labels that each got.

#5221 feat(typescript-plugin): skip declaration files in goto components definition
  packages/language-service/index.ts
  packages/typescript-plugin/lib/common.ts
Labels: version: minor

#5245 fix(language-core): transform slot parameter list into equivalent binding pattern
  packages/language-core/lib/codegen/globalTypes.ts
  packages/language-core/lib/codegen/template/vSlot.ts
Labels: ready for review

#5283 chore(vscode): correct `directory` path in package.json
  extensions/vscode/package.json
Labels: 🧹 p1-chore
