Repository vuejs/language-tools, pull requests merged in 2025-02, with the labels that each got.

#5160 chore: ask user to reload extension host when configuration changes
  extensions/vscode/src/languageClient.ts
Labels: 🍰 p2-nice-to-have

#5083 fix(language-core): intersect `__VLS_slots` with `__VLS_ctx.$slots`
  packages/language-core/lib/codegen/globalTypes.ts
  packages/language-core/lib/codegen/template/context.ts
  packages/language-core/lib/codegen/template/index.ts
  packages/language-core/lib/codegen/template/slotOutlet.ts
  packages/tsc/tests/__snapshots__/dts.spec.ts.snap
  test-workspace/tsc/passedFixtures/vue3/slots/main.vue
Labels: 🔨 p3-minor-bug, ready for review

#5141 feat(language-core): add `checkUnknownDirectives` option
  packages/language-core/lib/codegen/script/scriptSetup.ts
  packages/language-core/lib/codegen/template/context.ts
  packages/language-core/lib/codegen/template/elementDirectives.ts
  packages/language-core/lib/types.ts
  packages/language-core/lib/utils/ts.ts
  packages/language-core/schemas/vue-tsconfig.schema.json
Labels: enhancement, ready for review

#5045 feat(language-service): map sfc compiler errors outside the template inner content
  packages/component-meta/lib/base.ts
  packages/language-core/lib/virtualFile/vueFile.ts
  packages/language-service/lib/ideFeatures/nameCasing.ts
  packages/language-service/lib/plugins/vue-autoinsert-dotvalue.ts
  packages/language-service/lib/plugins/vue-complete-define-assignment.ts
  packages/language-service/lib/plugins/vue-document-drop.ts
  packages/language-service/lib/plugins/vue-document-links.ts
  packages/language-service/lib/plugins/vue-extract-file.ts
  packages/language-service/lib/plugins/vue-inlayhints.ts
  packages/language-service/lib/plugins/vue-sfc.ts
  packages/language-service/lib/plugins/vue-template.ts
  packages/typescript-plugin/lib/common.ts
  packages/typescript-plugin/lib/requests/collectExtractProps.ts
Labels: 🍰 p2-nice-to-have, ready for review

#5151 fix(language-core): ignore latex block content
  packages/language-core/lib/plugins/file-md.ts
Labels: 🔩 p2-edge-case, ready for review

#4685 fix(language-service): typescript-semantic renaming first in style blocks
  packages/language-service/lib/plugins/css.ts
  packages/language-service/package.json
  pnpm-lock.yaml
Labels: 🍰 p2-nice-to-have, ready for review

#4819 feat(language-core): enhance single root nodes collection
  packages/language-core/lib/codegen/script/component.ts
  packages/language-core/lib/codegen/template/context.ts
  packages/language-core/lib/codegen/template/element.ts
  packages/language-core/lib/codegen/template/index.ts
  packages/language-core/lib/codegen/template/templateChild.ts
  packages/language-core/lib/types.ts
  packages/language-core/lib/utils/ts.ts
  packages/language-core/schemas/vue-tsconfig.schema.json
  test-workspace/tsc/passedFixtures/vue3/rootEl/child.vue
  test-workspace/tsc/passedFixtures/vue3/rootEl/main.vue
Labels: enhancement

#5176 chore(language-core): add docs for `@vue-expect-error` support
  packages/language-core/lib/codegen/template/context.ts
  packages/language-core/lib/codegen/template/element.ts
  packages/language-core/lib/codegen/template/elementProps.ts
  packages/language-service/lib/plugins/vue-directive-comments.ts
Labels: documentation, ready for review
